### ISSUE TITLE
'How to use' documentation

### ISSUE THREAD

**Issue by keyurpd** [xbrlus/wip-2016-01-31#2]
Regarding this repository; is there a documentation as to how to use the schemas, samples, etc. contained here?

**Comment by davidtauriello** [comment]
Hi Keyur – thanks for writing about this taxonomy; please see https://xbrl.us/2016-surety-wip for documentation.  I’ve also updated the latest release on GitHub with these details – https://github.com/xbrlus/wip-2016-01-31/releases 

Let me know if you have additional questions about the Surety Work in Process Taxonomy.
